### ISSUE TITLE
Issue with latest DirectColors commit

### ISSUE THREAD

**Issue by geertdaelemans** [le717/LDR-Importer#105]
The commit that happened on August 7, broke some of my test files. I have attached the error message. Based upon one recognizable reference, I concluded (maybe too harshly) that it is somehow related to the DirectColors update. Don't shoot me if this does not make sense. ;-)

![bug report direct colors](https://cloud.githubusercontent.com/assets/11313559/9174206/bb142962-3f7e-11e5-87d7-610f36b444aa.png)

I can share the failing composition, if someone explains me how we are supposed to do this in GitHub. ;-)

Btw can anyone explain me how I avoid making a screendumps of the Blender console? IS there a place where I can find the actual log?

Cheers,

Geert

**Comment by le717** [comment]
**sigh*\* How did I almost know something somewhere would break in those PRs...

The best way to share a model is either to create a [Gist](https://gist.github.com/) of the contents or (if for some reason the problem can't be recreated that way), upload it to a LEGO-oriented file host site.I recommend [Bricksafe](http://bricksafe.com/).

> Btw can anyone explain me how I avoid making a screendumps of the Blender console? IS there a place where I can find the actual log?

Except that _is_ the actual log. ;)

**Comment by geertdaelemans** [comment]
Cool. Here is my first ever Gist: 
https://gist.github.com/geertdaelemans/531ee1c092937017c702
This file contains an Unofficial Model from "Holly Wood". It imported without problem before the latest commit.

Ah, somehow I was aware that the console was the actual log, he he. But I was wondering if I could actually cut and past the messages. When there is an amazing amount of messages, I would love to be able to read those that aren't in the buffer anymore. I read somewhere that clicking on the left corner of the console > edit > mark (did I tell you I use Windows?) is a solution. But it only got me to go crazy and start chasing cats...

**Comment by geertdaelemans** [comment]
Euhm, it says that I closed this? Did I? I am not aware...

**Comment by geertdaelemans** [comment]
Ah, I see... I learn every day -> push the green button!
