### ISSUE TITLE
Install errors on OS X with version 1, 3, 0

### ISSUE THREAD

**Issue by ghost** [le717/LDR-Importer#108]
Receive errors when trying to activate the latest version of the LDR-import plugin (Version 1.3.0) on OS X (Yosemite). See below:

Traceback (most recent call last):
  File "/Users/******/Documents/Blender Bits/blender-2.75-cc60f35-OSX-10.6-x86_64/blender.app/Contents/MacOS/../Resources/2.75/scripts/modules/addon_utils.py", line 324, in enable
    mod = __import__(module_name)
  File "/Users/******/Library/Application Support/Blender/2.75/scripts/addons/LDR-Importer-master/__init__.py", line 23, in <module>
    from . import import_ldraw
  File "/Users/******/Library/Application Support/Blender/2.75/scripts/addons/LDR-Importer-master/import_ldraw.py", line 1004, in <module>
    class LDRImporterOps(bpy.types.Operator, ImportHelper):
  File "/Users/******/Library/Application Support/Blender/2.75/scripts/addons/LDR-Importer-master/import_ldraw.py", line 1028, in LDRImporterOps
    default=prefs.findLDraw()
  File "/Users/******/Library/Application Support/Blender/2.75/scripts/addons/LDR-Importer-master/src/ldutils.py", line 134, in findLDraw
    for path in self.__paths[self.__curPlatform]:
KeyError: None

Same error on version 2.73, 2.74 and 2.75 of Blender. All previous preferences, settings and scripts for Blender removed.

Hope this helps.

**Comment by le717** [comment]
Alright, I see where the error is coming in, but in order me to fix it, I need you to run [this little script](https://gist.github.com/le717/75d65da4cf350edf75cf) and report back the output. Basically, I am failing to correctly detect that you are running OS X, and that script will get me the information I need. :)

**Comment by onaqc** [comment]
Output from your script is:

Darwin

Do you need anything else?

**Comment by onaqc** [comment]
Since all versions of OS X run on Darwin kernel, this might help:
  System Version:	OS X 10.10.5 (14F27)
  Kernel Version:	Darwin 14.5.0

**Comment by onaqc** [comment]
That worked a treat. I have my LDraw folder within the Bricksmith on my Mac folder so i added the extra path for this to your script.

            "mac": [
                "/Applications/LDraw/",
                "/Applications/ldraw/",
                "/Applications/Bricksmith/ldraw/",
            ],

I believe that i may have put the LDraw folder inside Bricksmith when i originally installed it many years ago.

If the LDR-addon cannot find the LDraw folder on a Mac it defaults to the windows Path; C:/LDraw

**Comment by le717** [comment]
>  I have my LDraw folder within the Bricksmith on my Mac folder so i added the extra path for this to your script.

You do not have to do that. In the Blender UI where you select the model to import, in the bottom left there are some import options. If you change the path there to your path, the script will remember it and use it every time.

> If the LDR-addon cannot find the LDraw folder on a Mac it defaults to the windows Path

This is by design. The majority of the users will be on Windows, but on any platform if the path cannot be found, we fall back to C:\LDraw, the original LDRAW.exe installation location. :)
