### ISSUE TITLE
Missing LDraw Search Path on Linux

### ISSUE THREAD

**Issue by weegreenblobbie** [le717/LDR-Importer#113]
Some tutorial out there had me install the ldraw parts in to `~/.ldraw` which isn't currently in the search path of the import script.  I tested this by adding `'~/.ldraw/` to the set of search paths.

This modification didn't work however, and I traced to down to not expanding the `~` character.  So I added the code:

    try:
        FinalLDrawDir = os.path.expanduser(FinalLDrawDir)
    except:
        pass

around line 1046.  Then it worked!

**Comment by le717** [comment]
I just took a look at this. Will you uninstall the script you have then install [this version](https://github.com/le717/LDR-Importer/archive/issue-113.zip)? Select the whole zip archive in the Blender file selection window (there's been some large changes that require a complete uninstall/reinstall).

**Comment by weegreenblobbie** [comment]
Looks like it worked right out of the box!  Thanks!
