### ISSUE TITLE
problem: 'cannot find c:/Ldraw'

### ISSUE THREAD

**Issue by karelrosseel** [le717/LDR-Importer#115]
The plug-in is not working, how comes? 
I get the failure 'can not find C:/Ldraw'
Thanks
Karel

**Comment by le717** [comment]
You are running Windows, correct? Can you confirm the [LDraw parts library](http://www.ldraw.org/) is installed at C:\LDraw

**Comment by karelrosseel** [comment]
I found the file LDconfig.ldr file  on C:\Users\Public\Documents\LDraw so I changed my directory.
For the parts of EV3 next generation are there not yet 3D drawings in ldd.lego.com.
I tried one custom project wielbasis.lxf, exported to wielbasis.Lrd but the wheels are not imported, strange.. Do you know why?
I tested an original drawing into Ldd and than the wheels com into blender. 
Please can you try and say me why my wheels are not imported into blender?
files attached
karel
[2 projects.zip](https://github.com/le717/LDR-Importer/files/110973/2.projects.zip)

**Comment by le717** [comment]
Closing issue as problem has been solved.
