### ISSUE TITLE
Can't install 1.3.1

### ISSUE THREAD

**Issue by virtualrepublic** [le717/LDR-Importer#119]
I can't install 1.3.1 with BLENDER 2.76b.

1.2.0 works.

1.3.1 will show an error: Missing script files

**Comment by le717** [comment]
That's because the plugin no longer resides in a single file. If you read the notice I have on the release you would have seen that. ;) See the [installation directions](https://github.com/le717/LDR-Importer/wiki/Installation) for details on installing v1.3.0+.

**Comment by virtualrepublic** [comment]
Thanks for the fast reply. I was trapped in the old 1.2.0 routine. :-)

**Comment by le717** [comment]
No problem. I kinda expected this type of issue to pop up.
