### ISSUE TITLE
Model file contents too short to extract header

### ISSUE THREAD

**Issue by rv12sp** [le717/LDR-Importer#124]
Mac OSX 10.10.5 Blender 2.77. Downloaded LDR-Importer today 1.31, created a 3 brick model in Leo cad saved as LDR. Installed the add-on and set the path to the LDraw Library (also downloaded today). Get the following error in the console (Launching Blender from the Console so the output stays there).

[LDR Importer] (11:41:02.76) Attempting to import /Users/clucier/Desktop/Bricktest2.ldr

[LDR Importer] (11:41:02.76) Parsing LDConfig.ldr

[LDR Importer] (11:41:02.76) ERROR: IndexError
Traceback (most recent call last):
  File "/Users/clucier/Library/Application Support/Blender/2.77/scripts/addons/io_scene_ldrimporter/import_ldraw.py", line 799, in create_model
    LDrawFile(context, fileName, 0, trix)
  File "/Users/clucier/Library/Application Support/Blender/2.77/scripts/addons/io_scene_ldrimporter/import_ldraw.py", line 83, in __init__
    self.parse(filename)
  File "/Users/clucier/Library/Application Support/Blender/2.77/scripts/addons/io_scene_ldrimporter/import_ldraw.py", line 203, in parse
    isPart = isTopLevelPart(lines[3])
IndexError: list index out of range

[LDR Importer] (11:41:02.76) ERROR: Reason: IndexError.

**Comment by le717** [comment]
I found the bug, will try to fix it this afternoon. Would you mind posing your model so I can fully recreate this bug?

**Comment by rv12sp** [comment]
Thanks for the quick response. Living in Nairobi and its the rainy season so planned on playing all weekend :)

Be careful this model is huge (all three bricks :)
[Bricktest2.ldr.zip](https://github.com/le717/LDR-Importer/files/252075/Bricktest2.ldr.zip)

**Comment by rv12sp** [comment]
Posted Thank You


Sent from my Samsung device

-------- Original message --------

**Comment by le717** [comment]
I've pushed a fix. Please uninstall the plugin and install [this version](https://github.com/le717/LDR-Importer/archive/issue-124.zip) and let me know if it it works now.

**Comment by rv12sp** [comment]
Thanks will try it today, waiting for a blender physics bake to finish, been running about 16 hours.

**Comment by CrownedComedian** [comment]
16 hours!!!???  What awesomeness are you working on, I must know!

**Comment by rv12sp** [comment]
The Base explosion to a lot of lego destruction. Baling in smoke fire and....melting plastic.


Sent from my Samsung device

-------- Original message --------

**Comment by rv12sp** [comment]
Thanks a lot, the version you uploaded imported with no errors.
