### ISSUE TITLE
"Basic Cleanup" function corrupts LEGO logo in open studs

### ISSUE THREAD

**Issue by Copperplate** [le717/LDR-Importer#128]
Hello all,

Firstly let me state what a fantastic program this importer is... thanks to all of you for your hard work in developing this plug-in!

I've come across an issue where if the Basic Cleanup button is checked, and you're importing Standard Primitives that have the stud.dat and stud2.dat files modified [as described here](http://forums.ldraw.org/showthread.php?tid=11439&pid=11504#pid11504), the open studs will have the LEGO logo partially destroyed. However, if you leave Basic Cleanup off, and then manually remove doubles (and add edge split), the logo is fine. This can be seen with parts such as 98100, and 44728. I've also noticed the gear-like sides of 44302 get corrupted during this as well, but are fine if done manually.

Thanks so much.

~Adam

**Comment by Copperplate** [comment]
I should mention that this is with stud-logo5.dat and stud2-logo5.dat as the replacement files. If using stud-logo4, then logo on the closed studs will also get corrupted by the automated basic cleanup function.

**Comment by virtualrepublic** [comment]
You need to use a higher scaling for import.

**Comment by Copperplate** [comment]
Thanks, virtualrepublic! Using a scale greater than 1 does seem to help. :1st_place_medal:
