### ISSUE TITLE
FBX export is not supporting Cycles nodes

### ISSUE THREAD

**Issue by virtualrepublic** [le717/LDR-Importer#129]
Exporting an LDRAW model to FBX will just give white materials. Older imports used one Diffuse BSDF but the new import will use a Glossy BSDF with a Mix Shader node. It looks like that this isn't supported by FBX. Switching to Blender Render will show the exact result of the FBX export.

Reproduction steps:
- import LDRAW
- export to FBX
- import FBX
Result: all colors are white

**Comment by pbeart** [comment]
Use the 'Blender materials to Cycles' (I think) plugin to transfer materials. This is a Blender issue
