### ISSUE TITLE
Problem: cannot find Ldraw installation at c:\  

### ISSUE THREAD

**Issue by Raymondvong** [le717/LDR-Importer#130]
I am using Blender V2.78 with MAC.

After I import with LDR-importer, it pop up a message 'cannot find Ldraw installation at c:\ '

**Comment by le717** [comment]
You have to download the LDraw Parts Library from http://ldraw.org/ first. Afterward, the script will attempt to automatically find the library. If it cannot, after going to File>Import, look at the left bar for some text called "LDraw Installation Path". Enter the correct path to the Library, and you should be fine after that.
