### ISSUE TITLE
Cannot Find LDraw Installation at C:/Ldraw

### ISSUE THREAD

**Issue by ghost** [le717/LDR-Importer#133]
I just installed the script in Blender 2.79 on Mac OSX 10.11.6 and when I try to import a file I get this error. Obviously on mac I have no C: drive so I have no idea what to try to fix it. Any suggestions?

**Comment by jasperges** [comment]
You can download the parts library from [here](http://ldraw.org/library/). Unzip it and put it wherever you like. Then change the path in Blender to that folder. For example if you put it in `/Users/rasketldn/ldraw` (I have no idea what your username is, so I'm making it up 😄), enter that folder in the import LDR options. (As a quick tip: in Finder you can copy the path. Right click on the `ldraw` folder, hold <kbd>option/alt</kbd> and choose `Copy "ldraw" as Pathname`.)

![screen shot 2017-12-13 at 15 07 48](https://user-images.githubusercontent.com/3788756/33942849-8b39a8de-e017-11e7-857a-e94685ef7927.png)

**Comment by ghost** [comment]
Thanks, right after posting I carried on looking for documentation and found a lot of this out! My fault for not reading properly.

It's kind of working now, I can import things, but there are many bricks missing from every scene I try to export. For example, [here on the right is what i'm exporting and on the left is what comes in.](https://i.imgur.com/vc1yMh2.png) Is it because there are other libraries I need?

**Comment by ghost** [comment]
I'm going to guess this is the answer?

http://www.ldraw.org/article/14.html#AllParts

**Comment by le717** [comment]
If you place the LDraw library in `/Applications/ldraw/` or `/Applications/LDraw/`, the script will automatically pick it up. If you think there's another place it should look to find the library, let me know and I can add it to the search path!
