### ISSUE TITLE
LDD to LDR, missing pieces, moved pieces

### ISSUE THREAD

**Issue by henhouse73** [le717/LDR-Importer#135]
Hi all. I'm trying to render a model using Blender. I'm going through the process of exporting from LDD to LDR. However, when I open the file on LDR the model is severely corrupted - pieces missing, pieces turned, colour changes, etc. What am I doing wrong?

**Comment by Copperplate** [comment]
I would recommend not creating your model in LDD, but directly in an LDraw application (I use LeoCad). There are plenty of pieces in LDD that are not included in the LDraw library, so they won't show up in LDraw. If there is a missing piece you need, however, see if it's available as an unofficial part or check the library here: [](http://www.digital-bricks.de/en/index.php?site=lddp&mg=244) You can also download the converter from the same site to change a part from LDD to LDR.
