### ISSUE TITLE
Traceback call issue

### ISSUE THREAD

**Issue by VivaPlays** [le717/LDR-Importer#138]
![image](https://user-images.githubusercontent.com/47909772/53281615-a8919c00-377f-11e9-8b73-bc3dc82bdb8e.png)

**Comment by le717** [comment]
I'm not exactly sure what's happening here. It looks like you've somehow set your LDraw path to `C:\Users\user\Downloads\%CommonDocumentsFolder%\ldraw` and that is triggering an error in Python itself. Double-check that the path to your copy of the LDraw library is set correctly and try again.
