### ISSUE TITLE
Inconsistent faces, triangles connecting to n-gons 

### ISSUE THREAD

**Issue by Knightoffaith** [le717/LDR-Importer#91]
In addition to #90 there are other issues that are occurring in the mesh creation which mean problems for CGI. I was in the Blender Freenode channel when I was having an issue with an LDraw mesh, and this is what I was told about. I honestly didn't completely understand these as well myself, so please just take a look at the conversation: http://www.pasteall.org/54310/text

**Comment by le717** [comment]
Tooltip added, will be in next version. I didn't know one was already written on an old branch. Closing.
