### ISSUE TITLE
Consolidate materials

### ISSUE THREAD

**Issue by Knightoffaith** [le717/LDR-Importer#92]
It seems that currently each vertex is assigned a new material. Could this pleased be changes so that there is only one material per color? It's a pain if I want to go in and change the color, and just a bit of a mess. Could probably be done using a simple switch to see if the material already exists, or such.

**Comment by le717** [comment]
@Knightoffaith I have a PR that fixes this up at #103, if you'd like to confirm that it works for you.

**Comment by Knightoffaith** [comment]
I'm away from my computer at the time being, but I'll try to give it a look Sunday.

Just wanted to let you know I saw this and will look into it as soon as I'm able to.

**Comment by le717** [comment]
That's fine. I am working on getting a PR merged before I merge it, and that probably won't get cleared up until this weekend anyway.
