### ISSUE TITLE
Weird gaps in between bricks

### ISSUE THREAD

**Issue by BertVanRaemdonck** [le717/LDR-Importer#95]
Right now, the importer creates gaps in between the bricks by resizing each part uniformly. the problem with this is that parts that are long but not very wide, say you have a surface tiled with 1x8s, will have quite large gaps between the small sides, but unnoticeable ones between the large sides. 
Another and probably better option is to resize each part non-uniformly, according to the dimension in every direction, so that the difference between the original part and the rescaled part is exactly the same in every direction. This will deform the mesh though, but so far it hasn't been noticeable to me, while the inconsistency in gaps has.
I've implemented this alterantive gap feature in the importer, and will create a branch with it.

**Comment by le717** [comment]
Fixed by #118.
